name       : tcsh
version    : 6.20.00
release    : 2
source     :
    - http://fossies.org/linux/misc/tcsh-6.20.00.tar.gz : b89de7064ab54dac454a266cfe5d8bf66940cb5ed048d0c30674ea62e7ecef9d
license    : BSD-3-clause
component  : system.utils
summary    : tcsh is a Unix shell based on and compatible with the C shell (csh).
description: |
    tcsh is a Unix shell based on and compatible with the C shell (csh).
setup      : |
    sed -i 's|SVID_SOURCE|DEFAULT_SOURCE|g' config/linux
    sed -i 's|BSD_SOURCE|DEFAULT_SOURCE|g'  config/linux

    %configure --bindir=/bin
build      : |
    %make
install    : |
    %make_install
