name       : tcsh
version    : '20210426'
release    : 5
source     :
    - https://github.com/tcsh-org/tcsh/archive/refs/tags/TCSH6_22_04.tar.gz : bb83740952115e5ccbe37eef484d536196a1c641460bdb4003735c3370dcf285
license    : BSD-3-clause
component  : system.utils
summary    : tcsh is a Unix shell based on and compatible with the C shell (csh).
description: |
    tcsh is a Unix shell based on and compatible with the C shell (csh).
setup      : |
    sed -i 's|SVID_SOURCE|DEFAULT_SOURCE|g' config/linux
    sed -i 's|BSD_SOURCE|DEFAULT_SOURCE|g'  config/linux

    %configure --bindir=/bin
build      : |
    %make
install    : |
    %make_install
