name       : tcsh
version    : '20170131'
release    : 3
source     :
    - https://github.com/tcsh-org/tcsh/archive/cvs2git-20170131.tar.gz : 1414046d65abe4f533fe8c9b099995c555072facc9f90c0c9c03bd574a17c8d8
license    : BSD-3-clause
component  : system.utils
summary    : tcsh is a Unix shell based on and compatible with the C shell (csh).
description: |
    tcsh is a Unix shell based on and compatible with the C shell (csh).
setup      : |
    sed -i 's|SVID_SOURCE|DEFAULT_SOURCE|g' config/linux
    sed -i 's|BSD_SOURCE|DEFAULT_SOURCE|g'  config/linux

    %configure --bindir=/bin
build      : |
    %make
install    : |
    %make_install
